name: ðŸ› Bug
description: Report a bug or crash.
title: "[Bug]: "
labels:
  - "type: bug"
  - "status: pending triage"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Clicking the button does not trigger...
      description: Include a clear and concise description of what is ACTUALLY HAPPENING, that you consider it unintended and problematic.
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Logs and/or Crash Report
      description: >
        We need the crash report to figure out why the crash happened.
        This file can be found in the \"crash-reports\" folder of your Minecraft folder.
        It will be the newest file there.
        Please upload the file to https://mclo.gs/ and put the link here.
        Do **not** paste the *contents* of the file here, because that will make this issue very hard to read.
        If you cannot provide it for any reason, put a "none available" here.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide an easy to follow set of steps to reproduce this bug.
      placeholder: |
        1. Load the game
        2. Go to ...
        3. (The world has detonated)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment information
      description: Please provide your Loader, MC and all the mods installed with their versions.