name: ✨ Feature
description: Request a new feature or propose an improvement.
title: "[Feat]: "
labels:
  - "type: feature"
  - "status: pending triage"
body:
  - type: textarea
    attributes:
      label: My suggestion
      description: Describe the changes you're suggesting and how they work.
      placeholder: Add an option to...
    validations:
      required: true

  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
        - label: Are you sure that this feature doesn't already exist?
        - label: Do you think that it will improve the mod?